# Generated by Django 6.0.6 on 2026-06-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MATH', 'Mathematics'), ('MTHL', 'Mathematical Literacy'), ('PHYS', 'Physical Sciences'), ('LFSC', 'Life Sciences'), ('ENGL', 'English Home Language'), ('FAL', 'First Additional Language'), ('ACC', 'Accounting'), ('IT', 'Information Technology'), ('CAT', 'Computer Applications Technology')], max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('term', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3'), (4, 'Term 4')])),
                ('year', models.IntegerField(default=2026)),
            ],
        ),
    ]
