# Generated by Django 6.0.6 on 2026-06-12 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termmark',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='authentication.studentprofile'),
        ),
        migrations.AddField(
            model_name='termmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='termmark',
            unique_together={('profile', 'subject', 'term', 'year')},
        ),
    ]
